"use client";
import { useEffect, useState, useRef } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, User, Mail, Phone, Briefcase, Sparkles, AlertTriangle, CheckCircle, TrendingUp, Zap, Target, BookOpen, GraduationCap, Award } from 'lucide-react';
import api from '@/lib/api';

export default function ResumeViewer() {
  const { id } = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const urlRole = searchParams.get('role');
  
  const [parsedData, setParsedData] = useState<any>(null);
  const [feedback, setFeedback] = useState<any>(null);
  const [loadingFeedback, setLoadingFeedback] = useState(false);
  const [targetRole, setTargetRole] = useState(urlRole || "");
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    const fetchParsedData = async () => {
      try {
        const response = await api.get(`/api/resume/${id}/parsed`);
        setParsedData(response.data.parsed_json);
      } catch (err) {
        console.error('Failed to fetch parsed data', err);
      }
    };
    fetchParsedData();
  }, [id]);

  useEffect(() => {
    if (parsedData && urlRole && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateFeedback(urlRole);
    }
  }, [parsedData, urlRole]);

  const generateFeedback = async (roleToUse?: string) => {
    const role = typeof roleToUse === 'string' ? roleToUse : targetRole;
    setLoadingFeedback(true);
    try {
      const response = await api.post(`/api/resume/${id}/feedback`, {
        target_role: role || null
      });
      let parsedFeedback = null;
      try {
        parsedFeedback = JSON.parse(response.data.feedback_text);
      } catch (e) {
        console.log("Could not parse feedback as JSON, using raw text", e);
      }
      setFeedback({
        ...response.data,
        structured_data: parsedFeedback
      });
    } catch (err) {
      console.error('Failed to generate feedback', err);
    } finally {
      setLoadingFeedback(false);
    }
  };

  if (!parsedData) return (
    <div className="min-h-screen mesh-bg flex items-center justify-center">
      <div className="flex flex-col items-center gap-4">
        <div className="w-10 h-10 border-4 border-primary/30 border-t-primary rounded-full animate-spin"></div>
        <p className="text-zinc-400 font-medium">Loading Analysis...</p>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen mesh-bg relative p-8 pb-24 overflow-hidden">
      {/* Decorative Elements */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-primary/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-96 h-96 bg-purple-500/10 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-7xl mx-auto space-y-8 relative z-10">
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 glass-panel p-6 rounded-2xl shadow-sm border border-white/10">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={() => router.push('/dashboard')} className="rounded-full hover:bg-white/10 text-zinc-400 hover:text-white">
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-white">
                Resume Insights
              </h1>
              <p className="text-zinc-400 mt-1">Review extracted details and AI evaluation</p>
            </div>
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Left Column: Parsed Data */}
          <div className="lg:col-span-5 space-y-6">
            <Card className="border-0 shadow-lg glass-panel rounded-3xl overflow-hidden bg-black/20">
              <div className="h-1.5 w-full bg-gradient-to-r from-primary to-purple-500"></div>
              <CardHeader className="pb-4 border-b border-white/10">
                <CardTitle className="text-xl flex items-center gap-2 text-white">
                  <User className="w-5 h-5 text-primary" /> Candidate Profile
                </CardTitle>
                <CardDescription className="text-zinc-400">Extracted contact and basic info</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6 pt-6">
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <div className="p-2 bg-primary/20 rounded-lg"><User className="w-4 h-4 text-primary" /></div>
                    <div>
                      <p className="text-sm text-zinc-400 font-medium">Full Name</p>
                      <p className="font-semibold text-white">{parsedData.name || 'Not detected'}</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="p-2 bg-sky-500/20 rounded-lg"><Mail className="w-4 h-4 text-sky-400" /></div>
                    <div>
                      <p className="text-sm text-zinc-400 font-medium">Email Address</p>
                      <p className="font-semibold text-white">{parsedData.email || 'Not detected'}</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="p-2 bg-indigo-500/20 rounded-lg"><Phone className="w-4 h-4 text-indigo-400" /></div>
                    <div>
                      <p className="text-sm text-zinc-400 font-medium">Phone Number</p>
                      <p className="font-semibold text-white">{parsedData.phone || 'Not detected'}</p>
                    </div>
                  </div>
                </div>

                <div className="pt-4 border-t border-white/10">
                  <div className="flex items-center gap-2 mb-3">
                    <Zap className="w-5 h-5 text-sky-400" />
                    <span className="font-semibold text-white">Detected Skills</span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {parsedData.skills?.map((skill: string, idx: number) => (
                      <Badge key={idx} variant="secondary" className="bg-white/10 text-zinc-200 hover:bg-white/20 px-3 py-1 text-sm font-medium border border-white/10">
                        {skill}
                      </Badge>
                    ))}
                    {(!parsedData.skills || parsedData.skills.length === 0) && (
                      <p className="text-sm text-zinc-500 italic">No specific skills detected by parser.</p>
                    )}
                  </div>
                </div>

                {parsedData.experience && (
                  <div className="pt-4 border-t border-white/10">
                    <div className="flex items-center gap-2 mb-3">
                      <Briefcase className="w-5 h-5 text-primary" />
                      <span className="font-semibold text-white">Experience Highlights</span>
                    </div>
                    <div className="bg-white/5 p-4 rounded-xl max-h-48 overflow-y-auto text-sm text-zinc-300 custom-scrollbar border border-white/10">
                      <pre className="whitespace-pre-wrap font-sans leading-relaxed">{parsedData.experience}</pre>
                    </div>
                  </div>
                )}

                {parsedData.education && (
                  <div className="pt-4 border-t border-white/10">
                    <div className="flex items-center gap-2 mb-3">
                      <GraduationCap className="w-5 h-5 text-indigo-400" />
                      <span className="font-semibold text-white">Education Background</span>
                    </div>
                    <div className="bg-white/5 p-4 rounded-xl max-h-32 overflow-y-auto text-sm text-zinc-300 custom-scrollbar border border-white/10">
                      <pre className="whitespace-pre-wrap font-sans leading-relaxed">{parsedData.education}</pre>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Right Column: AI Feedback */}
          <div className="lg:col-span-7 space-y-6">
            {!feedback ? (
              <Card className="border-0 shadow-md glass-panel rounded-3xl h-full flex flex-col justify-center p-8 min-h-[400px] bg-black/20">
                <div className="max-w-md mx-auto text-center space-y-6 w-full">
                  <div className="p-4 bg-primary/20 rounded-full w-20 h-20 mx-auto flex items-center justify-center shadow-inner">
                    {loadingFeedback ? (
                      <div className="w-10 h-10 border-4 border-primary/30 border-t-primary rounded-full animate-spin"></div>
                    ) : (
                      <Sparkles className="w-10 h-10 text-primary" />
                    )}
                  </div>
                  
                  <div>
                    <h3 className="text-2xl font-bold text-white mb-2">
                      {loadingFeedback ? 'Analyzing Resume...' : 'Simulate ATS Evaluation'}
                    </h3>
                    <p className="text-zinc-400">
                      {loadingFeedback 
                        ? 'Our AI is currently acting as a strict ATS to evaluate your fit.'
                        : 'Provide a target role to get a realistic, tailored ATS match score and feedback.'}
                    </p>
                  </div>
                  
                  {!loadingFeedback && (
                    <>
                      <div className="relative group text-left">
                        <label className="text-sm font-bold text-zinc-300 mb-1.5 flex items-center gap-1.5 ml-1">
                          <Target className="w-4 h-4 text-primary" /> Target Role (Optional)
                        </label>
                        <input 
                          type="text" 
                          placeholder="e.g. Senior Software Engineer"
                          value={targetRole}
                          onChange={(e) => setTargetRole(e.target.value)}
                          className="w-full px-5 py-4 bg-white/5 border border-white/10 rounded-2xl focus:border-primary focus:ring-4 focus:ring-primary/20 outline-none transition-all text-white font-medium placeholder:text-zinc-600 shadow-sm"
                        />
                      </div>

                      <Button 
                        onClick={() => generateFeedback()} 
                        disabled={loadingFeedback}
                        size="lg"
                        className="w-full rounded-2xl h-14 bg-primary hover:bg-primary/90 shadow-[0_0_20px_rgba(147,51,234,0.3)] hover:shadow-[0_0_30px_rgba(147,51,234,0.5)] transform hover:-translate-y-1 transition-all text-lg font-bold text-white"
                      >
                        <span className="flex items-center gap-2">
                          <Sparkles className="w-5 h-5" /> Generate ATS Score
                        </span>
                      </Button>
                    </>
                  )}
                </div>
              </Card>
            ) : (
              <div className="space-y-6 animate-in slide-in-from-bottom-4 duration-500">
                {/* Score Header */}
                <Card className="border-0 shadow-lg bg-gradient-to-br from-indigo-900 to-purple-900 text-white rounded-3xl overflow-hidden relative glass-panel">
                  <div className="absolute top-0 right-0 p-8 opacity-10">
                    <TrendingUp className="w-48 h-48" />
                  </div>
                  <CardContent className="p-8 relative z-10 flex flex-col md:flex-row items-center justify-between gap-6">
                    <div>
                      <h2 className="text-3xl font-extrabold mb-2 text-white">Resume Score {targetRole ? `for ${targetRole}` : ''}</h2>
                      <p className="text-indigo-200 max-w-md text-sm md:text-base leading-relaxed">
                        {feedback.structured_data?.summary || 'We evaluated your resume layout, content, and potential impact.'}
                      </p>
                    </div>
                    <div className="flex flex-col items-center justify-center bg-black/40 backdrop-blur-md rounded-full w-32 h-32 border-4 border-primary/50 flex-shrink-0 shadow-[0_0_30px_rgba(147,51,234,0.4)]">
                      <span className="text-4xl font-black text-white">{feedback.score}</span>
                      <span className="text-white/70 text-sm font-medium">/ 100</span>
                    </div>
                  </CardContent>
                </Card>

                {/* Structured Data UI */}
                {feedback.structured_data ? (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Card className="border-0 shadow-md rounded-2xl border-l-4 border-l-emerald-500 glass-panel bg-black/20">
                      <CardHeader className="pb-2">
                        <CardTitle className="text-lg flex items-center gap-2 text-white">
                          <CheckCircle className="w-5 h-5 text-emerald-400" /> Strengths
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2">
                          {feedback.structured_data.strengths?.map((str: string, i: number) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-zinc-300">
                              <span className="text-emerald-400 mt-0.5">•</span> {str}
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>

                    <Card className="border-0 shadow-md rounded-2xl border-l-4 border-l-rose-500 glass-panel bg-black/20">
                      <CardHeader className="pb-2">
                        <CardTitle className="text-lg flex items-center gap-2 text-white">
                          <AlertTriangle className="w-5 h-5 text-rose-400" /> Areas to Improve
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2">
                          {feedback.structured_data.weaknesses?.map((weak: string, i: number) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-zinc-300">
                              <span className="text-rose-400 mt-0.5">•</span> {weak}
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>

                    <Card className="border-0 shadow-md rounded-2xl md:col-span-2 border-l-4 border-l-sky-400 glass-panel bg-black/20">
                      <CardHeader className="pb-2">
                        <CardTitle className="text-lg flex items-center gap-2 text-white">
                          <BookOpen className="w-5 h-5 text-sky-400" /> Suggested Skills to Add
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="flex flex-wrap gap-2">
                          {feedback.structured_data.missing_skills?.map((skill: string, i: number) => (
                            <Badge key={i} variant="outline" className="border-sky-400/30 text-sky-300 bg-sky-500/10 px-3 py-1.5 text-sm shadow-sm">
                              {skill}
                            </Badge>
                          ))}
                        </div>
                      </CardContent>
                    </Card>

                    {feedback.structured_data.recommended_certifications && feedback.structured_data.recommended_certifications.length > 0 && (
                      <Card className="border-0 shadow-md rounded-2xl md:col-span-2 border-l-4 border-l-amber-400 glass-panel bg-black/20">
                        <CardHeader className="pb-2">
                          <CardTitle className="text-lg flex items-center gap-2 text-white">
                            <Award className="w-5 h-5 text-amber-400" /> Recommended Certifications
                          </CardTitle>
                        </CardHeader>
                        <CardContent>
                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                            {feedback.structured_data.recommended_certifications.map((cert: string, i: number) => (
                              <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-amber-500/10 border border-amber-500/20">
                                <div className="p-2 bg-amber-500/20 rounded-lg text-amber-400">
                                  <Award className="w-4 h-4" />
                                </div>
                                <span className="text-sm font-medium text-zinc-200">{cert}</span>
                              </div>
                            ))}
                          </div>
                        </CardContent>
                      </Card>
                    )}
                    
                    <div className="md:col-span-2 flex justify-end mt-4">
                        <Button 
                          onClick={() => { setFeedback(null); setTargetRole(""); router.replace(`/dashboard/resume/${id}`); }} 
                          variant="outline"
                          className="rounded-xl border-white/20 text-zinc-300 hover:bg-white/10 hover:text-white bg-transparent"
                        >
                          Target a Different Role
                        </Button>
                    </div>
                  </div>
                ) : (
                  <Card className="border-0 shadow-md rounded-2xl glass-panel bg-black/20">
                    <CardHeader>
                      <CardTitle className="text-white">Detailed Feedback</CardTitle>
                    </CardHeader>
                    <CardContent className="prose prose-invert max-w-none">
                      <p className="text-sm whitespace-pre-wrap text-zinc-300">{feedback.feedback_text}</p>
                      <Button onClick={() => setFeedback(null)} variant="outline" className="mt-4 border-white/20 text-zinc-300 hover:bg-white/10 hover:text-white bg-transparent">Target a Different Role</Button>
                    </CardContent>
                  </Card>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

