"use client";
import { useEffect, useState, useRef } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { ArrowLeft, User, Mail, Phone, Briefcase, Sparkles, GraduationCap, ArrowRight, CheckCircle2, AlertTriangle, ListOrdered, Edit3, Target, ArrowRightCircle } from 'lucide-react';
import api from '@/lib/api';
import { ThemeToggle } from '@/components/ThemeToggle';

// Simple Circular Progress Component
const CircularProgress = ({ value, color, size = 120, strokeWidth = 10 }: { value: number, color: string, size?: number, strokeWidth?: number }) => {
  const radius = (size - strokeWidth) / 2;
  const circumference = radius * 2 * Math.PI;
  const strokeDashoffset = circumference - (value / 100) * circumference;

  return (
    <div className="relative flex items-center justify-center" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="transform -rotate-90">
        {/* Background circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          stroke="currentColor"
          strokeWidth={strokeWidth}
          fill="transparent"
          className="text-foreground/5"
        />
        {/* Progress circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          stroke={color}
          strokeWidth={strokeWidth}
          fill="transparent"
          strokeDasharray={circumference}
          strokeDashoffset={strokeDashoffset}
          className="transition-all duration-1000 ease-out"
          strokeLinecap="round"
        />
      </svg>
      <div className="absolute flex flex-col items-center justify-center">
        <span className="text-3xl font-bold text-foreground leading-none">{value}</span>
      </div>
    </div>
  );
};

export default function ResumeViewer() {
  const { id } = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const urlRole = searchParams.get('role');
  
  const [parsedData, setParsedData] = useState<any>(null);
  const [feedback, setFeedback] = useState<any>(null);
  const [loadingFeedback, setLoadingFeedback] = useState(false);
  const [targetRole, setTargetRole] = useState(urlRole || "");
  const [activeTab, setActiveTab] = useState<'strengths' | 'improvements' | 'action_plan' | 'rewrites'>('strengths');
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    const fetchParsedData = async () => {
      try {
        const response = await api.get(`/api/resume/${id}/parsed`);
        setParsedData(response.data.parsed_json);
      } catch (err) {
        console.error('Failed to fetch parsed data', err);
      }
    };
    fetchParsedData();
  }, [id]);

  useEffect(() => {
    if (parsedData && urlRole && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateFeedback(urlRole);
    }
  }, [parsedData, urlRole]);

  const generateFeedback = async (roleToUse?: string) => {
    const role = typeof roleToUse === 'string' ? roleToUse : targetRole;
    setLoadingFeedback(true);
    try {
      const response = await api.post(`/api/resume/${id}/feedback`, {
        target_role: role || null
      });
      let parsedFeedback = null;
      try {
        parsedFeedback = JSON.parse(response.data.feedback_text);
      } catch (e) {
        console.log("Could not parse feedback as JSON, using raw text", e);
      }
      setFeedback({
        ...response.data,
        structured_data: parsedFeedback
      });
    } catch (err) {
      console.error('Failed to generate feedback', err);
    } finally {
      setLoadingFeedback(false);
    }
  };

  if (!parsedData) return (
    <div className="min-h-screen bg-background flex items-center justify-center">
      <div className="flex flex-col items-center gap-4">
        <div className="w-10 h-10 border-4 border-primary/30 border-t-primary rounded-full animate-spin"></div>
        <p className="text-muted-foreground font-medium">Loading Analysis...</p>
      </div>
    </div>
  );

  const structData = feedback?.structured_data;

  return (
    <div className="min-h-screen bg-background relative p-4 md:p-8 pb-24 font-sans text-[16px] overflow-hidden">
      {/* Decorative Elements */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary/5 rounded-full blur-[150px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-teal-500/5 rounded-full blur-[150px] pointer-events-none" />

      <div className="max-w-7xl mx-auto space-y-8 relative z-10">
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-card p-6 rounded-2xl shadow-sm border border-border">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={() => router.push('/dashboard')} className="rounded-full hover:bg-muted/50 text-muted-foreground hover:text-foreground">
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div>
              <h1 className="text-2xl font-bold tracking-tight text-foreground">
                Resume Insights
              </h1>
              <p className="text-muted-foreground mt-1 text-sm">Review extracted details and AI evaluation</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <ThemeToggle />
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Column: Candidate Profile & Skills */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bg-card border border-border rounded-3xl p-6 shadow-xl">
              <h2 className="text-lg font-bold text-foreground mb-6 flex items-center gap-2">
                <User className="w-5 h-5 text-primary" /> Candidate Profile
              </h2>
              
              <div className="space-y-5">
                <div className="flex items-start gap-4">
                  <div className="p-2.5 bg-muted/50 rounded-xl border border-border"><User className="w-4 h-4 text-muted-foreground" /></div>
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">Full Name</p>
                    <p className="font-medium text-zinc-200">{parsedData.name || 'Not detected'}</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="p-2.5 bg-muted/50 rounded-xl border border-border"><Mail className="w-4 h-4 text-muted-foreground" /></div>
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">Email Address</p>
                    <p className="font-medium text-zinc-200">{parsedData.email || 'Not detected'}</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="p-2.5 bg-muted/50 rounded-xl border border-border"><Phone className="w-4 h-4 text-muted-foreground" /></div>
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">Phone Number</p>
                    <p className="font-medium text-zinc-200">{parsedData.phone || 'Not detected'}</p>
                  </div>
                </div>
              </div>

              {parsedData.skills && parsedData.skills.length > 0 && (
                <div className="mt-8 pt-8 border-t border-border">
                  <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-4">Detected Skills</h3>
                  <div className="flex flex-wrap gap-2">
                    {parsedData.skills.map((skill: string, idx: number) => (
                      <span key={idx} className="bg-muted/50 border border-border text-muted-foreground px-3 py-1.5 rounded-full text-sm font-medium">
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {parsedData.experience && (
                <div className="mt-8 pt-8 border-t border-border">
                  <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-4 flex items-center gap-2">
                    <Briefcase className="w-4 h-4" /> Experience
                  </h3>
                  <div className="bg-background p-4 rounded-xl max-h-48 overflow-y-auto text-sm text-muted-foreground custom-scrollbar border border-border leading-relaxed">
                    <pre className="whitespace-pre-wrap font-sans">{parsedData.experience}</pre>
                  </div>
                </div>
              )}
              
              {parsedData.education && (
                <div className="mt-8 pt-8 border-t border-border">
                  <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-4 flex items-center gap-2">
                    <GraduationCap className="w-4 h-4" /> Education
                  </h3>
                  <div className="bg-background p-4 rounded-xl max-h-32 overflow-y-auto text-sm text-muted-foreground custom-scrollbar border border-border leading-relaxed">
                    <pre className="whitespace-pre-wrap font-sans">{parsedData.education}</pre>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Right Column: ATS Score & Feedback */}
          <div className="lg:col-span-8 space-y-6">
            {!feedback ? (
              <div className="bg-card border border-border rounded-3xl p-12 text-center shadow-xl h-full flex flex-col justify-center min-h-[500px]">
                <div className="max-w-sm mx-auto space-y-6">
                  <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4 border border-primary/20 shadow-[0_0_30px_rgba(147,51,234,0.2)]">
                    {loadingFeedback ? (
                      <div className="w-8 h-8 border-4 border-primary/30 border-t-primary rounded-full animate-spin"></div>
                    ) : (
                      <Sparkles className="w-8 h-8 text-primary" />
                    )}
                  </div>
                  
                  <h2 className="text-2xl font-bold text-foreground">
                    {loadingFeedback ? 'Simulating ATS...' : 'Run ATS Analysis'}
                  </h2>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    {loadingFeedback 
                      ? 'Our AI is evaluating your resume against industry standards.'
                      : 'Provide a target role to get an exact match score, keyword analysis, and bullet point rewrites.'}
                  </p>

                  {!loadingFeedback && (
                    <div className="space-y-4 pt-4">
                      <div className="text-left space-y-2">
                        <label className="text-xs uppercase tracking-wider font-semibold text-muted-foreground flex items-center gap-2 ml-1">
                          <Target className="w-4 h-4 text-primary" /> Target Role
                        </label>
                        <input 
                          type="text" 
                          placeholder="e.g. Senior Software Engineer"
                          value={targetRole}
                          onChange={(e) => setTargetRole(e.target.value)}
                          className="w-full px-4 py-3 bg-muted border border-border rounded-xl focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-all text-foreground font-medium placeholder:text-muted-foreground"
                        />
                      </div>
                      <Button 
                        onClick={() => generateFeedback()} 
                        disabled={loadingFeedback}
                        className="w-full bg-primary hover:bg-primary/90 text-foreground shadow-[0_0_20px_rgba(147,51,234,0.3)] h-12 rounded-xl font-semibold"
                      >
                        Generate Score
                      </Button>
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="space-y-6 animate-in slide-in-from-bottom-4 duration-500">
                {/* Score Rings Section */}
                <div className="bg-card border border-border rounded-3xl p-8 shadow-xl flex flex-col md:flex-row items-center gap-8 justify-between relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-[80px] pointer-events-none" />
                  
                  <div className="flex-1 space-y-3 z-10 text-center md:text-left">
                    <h2 className="text-2xl font-bold text-foreground">ATS Analysis Results</h2>
                    {targetRole && <p className="text-muted-foreground">Target Role: <span className="text-foreground font-medium">{targetRole}</span></p>}
                    <p className="text-muted-foreground text-sm leading-relaxed max-w-md">
                      {structData?.summary || 'We evaluated your resume layout, content, and potential impact against ATS systems.'}
                    </p>
                    <Button 
                      variant="outline" 
                      onClick={() => { setFeedback(null); setTargetRole(""); }} 
                      className="mt-4 border-border text-muted-foreground hover:bg-muted/50 hover:text-foreground rounded-lg h-9 px-4 text-sm bg-transparent"
                    >
                      Analyze Different Role
                    </Button>
                  </div>
                  
                  <div className="flex gap-8 z-10">
                    <div className="flex flex-col items-center gap-3">
                      <CircularProgress value={feedback.score} color="#a855f7" size={130} strokeWidth={12} />
                      <span className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">ATS Score</span>
                    </div>
                    {structData?.keyword_match_rate !== undefined && (
                      <div className="flex flex-col items-center gap-3">
                        <CircularProgress value={structData.keyword_match_rate} color="#14b8a6" size={130} strokeWidth={12} />
                        <span className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Keyword Match</span>
                      </div>
                    )}
                  </div>
                </div>

                {structData && (
                  <div className="space-y-6">
                    
                    {/* Tabs Navigation */}
                    <div className="flex gap-2 p-1 bg-card border border-border rounded-xl overflow-x-auto custom-scrollbar">
                      <button 
                        onClick={() => setActiveTab('strengths')}
                        className={`px-4 py-2.5 rounded-lg text-sm font-semibold transition-all whitespace-nowrap ${activeTab === 'strengths' ? 'bg-muted text-foreground' : 'text-muted-foreground hover:text-muted-foreground hover:bg-muted/50'}`}
                      >
                        Strengths
                      </button>
                      <button 
                        onClick={() => setActiveTab('improvements')}
                        className={`px-4 py-2.5 rounded-lg text-sm font-semibold transition-all whitespace-nowrap ${activeTab === 'improvements' ? 'bg-muted text-foreground' : 'text-muted-foreground hover:text-muted-foreground hover:bg-muted/50'}`}
                      >
                        Areas to Improve
                      </button>
                      <button 
                        onClick={() => setActiveTab('action_plan')}
                        className={`px-4 py-2.5 rounded-lg text-sm font-semibold transition-all whitespace-nowrap ${activeTab === 'action_plan' ? 'bg-muted text-foreground' : 'text-muted-foreground hover:text-muted-foreground hover:bg-muted/50'}`}
                      >
                        Action Plan
                      </button>
                      <button 
                        onClick={() => setActiveTab('rewrites')}
                        className={`px-4 py-2.5 rounded-lg text-sm font-semibold transition-all whitespace-nowrap ${activeTab === 'rewrites' ? 'bg-muted text-foreground flex items-center gap-2' : 'text-muted-foreground hover:text-muted-foreground hover:bg-muted/50 flex items-center gap-2'}`}
                      >
                        <Sparkles className="w-4 h-4" /> Bullet Rewrites
                      </button>
                    </div>

                    {/* Tab Content */}
                    <div className="bg-card border border-border rounded-3xl p-6 md:p-8 shadow-xl min-h-[300px]">
                      
                      {activeTab === 'strengths' && (
                        <div className="space-y-6 animate-in fade-in duration-300">
                          <h3 className="text-lg font-bold text-foreground flex items-center gap-2 mb-6">
                            <CheckCircle2 className="w-5 h-5 text-emerald-500" /> Key Strengths
                          </h3>
                          <div className="grid gap-4">
                            {structData.strengths?.map((str: string, i: number) => (
                              <div key={i} className="bg-muted border-l-4 border-l-emerald-500 rounded-r-xl p-5 border border-y-white/5 border-r-white/5 shadow-sm">
                                <p className="text-muted-foreground leading-relaxed text-sm">{str}</p>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {activeTab === 'improvements' && (
                        <div className="space-y-6 animate-in fade-in duration-300">
                          <h3 className="text-lg font-bold text-foreground flex items-center gap-2 mb-6">
                            <AlertTriangle className="w-5 h-5 text-amber-500" /> Areas to Improve
                          </h3>
                          <div className="grid gap-4">
                            {structData.weaknesses?.map((weak: string, i: number) => (
                              <div key={i} className="bg-muted border-l-4 border-l-amber-500 rounded-r-xl p-5 border border-y-white/5 border-r-white/5 shadow-sm">
                                <p className="text-muted-foreground leading-relaxed text-sm">{weak}</p>
                              </div>
                            ))}
                          </div>
                          
                          {structData.missing_skills && structData.missing_skills.length > 0 && (
                            <div className="mt-8 pt-8 border-t border-border">
                              <h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-4">Suggested Skills to Add</h4>
                              <div className="flex flex-wrap gap-2">
                                {structData.missing_skills.map((skill: string, i: number) => (
                                  <span key={i} className="bg-teal-500/10 text-teal-400 border border-teal-500/20 px-4 py-2 rounded-full text-sm font-medium">
                                    {skill}
                                  </span>
                                ))}
                              </div>
                            </div>
                          )}
                        </div>
                      )}

                      {activeTab === 'action_plan' && (
                        <div className="space-y-6 animate-in fade-in duration-300">
                          <h3 className="text-lg font-bold text-foreground flex items-center gap-2 mb-6">
                            <ListOrdered className="w-5 h-5 text-primary" /> Recommended Action Plan
                          </h3>
                          <div className="space-y-4">
                            {structData.actionable_improvements?.map((action: string, i: number) => (
                              <div key={i} className="flex items-start gap-4 p-5 rounded-xl bg-muted border border-border">
                                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary/20 text-primary flex items-center justify-center font-bold text-sm">
                                  {i + 1}
                                </div>
                                <p className="text-muted-foreground leading-relaxed mt-1 text-sm">{action}</p>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {activeTab === 'rewrites' && (
                        <div className="space-y-8 animate-in fade-in duration-300">
                          <div className="flex items-center justify-between">
                            <h3 className="text-lg font-bold text-foreground flex items-center gap-2">
                              <Edit3 className="w-5 h-5 text-indigo-400" /> AI Bullet Rewrites
                            </h3>
                            <span className="text-xs bg-indigo-500/20 text-indigo-300 px-3 py-1 rounded-full border border-indigo-500/20">
                              Impact-driven format
                            </span>
                          </div>
                          
                          <div className="flex flex-col gap-5">
                            {structData.bullet_point_rewrites?.map((rewrite: any, i: number) => (
                              <div key={i} className="flex flex-col md:flex-row gap-0 rounded-xl overflow-hidden border border-border shadow-sm group hover:-translate-y-1 transition-transform duration-300">
                                {/* Original Side */}
                                <div className="flex-1 bg-rose-500/5 p-6 relative">
                                  <span className="text-xs font-bold text-rose-500/70 uppercase tracking-wider mb-2 block">Original</span>
                                  <p className="text-muted-foreground italic text-sm leading-relaxed">"{rewrite.original}"</p>
                                </div>
                                
                                {/* Divider with Icon */}
                                <div className="hidden md:flex items-center justify-center bg-card px-3 z-10 relative">
                                  <div className="absolute top-0 bottom-0 w-px bg-muted/50 left-1/2 transform -translate-x-1/2"></div>
                                  <div className="w-8 h-8 rounded-full bg-muted border border-border flex items-center justify-center relative z-10">
                                    <ArrowRight className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors" />
                                  </div>
                                </div>
                                <div className="md:hidden flex items-center justify-center h-8 bg-card">
                                  <ArrowRight className="w-4 h-4 text-muted-foreground" />
                                </div>

                                {/* Improved Side */}
                                <div className="flex-1 bg-emerald-500/5 p-6 flex flex-col justify-between relative">
                                  <div>
                                    <span className="text-xs font-bold text-emerald-500/70 uppercase tracking-wider mb-2 block">Improved</span>
                                    <p className="text-zinc-200 font-medium text-sm leading-relaxed">"{rewrite.improved}"</p>
                                  </div>
                                  <div className="mt-4 pt-4 border-t border-emerald-500/10">
                                    <p className="text-xs text-muted-foreground leading-relaxed">
                                      <span className="text-primary font-bold mr-1">Why:</span>
                                      {rewrite.reasoning}
                                    </p>
                                  </div>
                                </div>
                              </div>
                            ))}
                            {(!structData.bullet_point_rewrites || structData.bullet_point_rewrites.length === 0) && (
                              <div className="text-center py-12 text-muted-foreground bg-muted rounded-xl border border-dashed border-border">
                                <p className="font-medium">No rewrites suggested.</p>
                                <p className="text-sm mt-1">Your bullet points are already strong!</p>
                              </div>
                            )}
                          </div>
                        </div>
                      )}

                    </div>
                  </div>
                )}
                
                {!structData && (
                  <div className="bg-card border border-border rounded-3xl p-8 shadow-xl">
                    <h3 className="text-lg font-bold text-foreground mb-4">Detailed Feedback</h3>
                    <p className="text-muted-foreground leading-relaxed whitespace-pre-wrap">{feedback.feedback_text}</p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
