"""Add status and notes to Application

Revision ID: 66601a500e3d
Revises: 928d7ab458b5
Create Date: 2026-06-15 15:39:00.805193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66601a500e3d'
down_revision: Union[str, Sequence[str], None] = '928d7ab458b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'notes')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
